os: linux
dist: bionic
language: python

services:
  - docker

jobs:
  include:
    - stage: Docker
      if: branch = master
      script:
           - sudo apt-get update
           - docker build -t docker-zmq-pub .
           - docker run -d --name docker-pub-server --network host -t docker-zmq-pub
           - docker exec docker-pub-server bash -c 'cd /app && curl -s -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip -o sonarscanner.zip && unzip -qq sonarscanner.zip && export PATH=$PATH:sonar-scanner-4.2.0.1873-linux/bin/ && apt-get install -y openjdk-8-jre && sonar-scanner -Dsonar.organization=incluit -Dsonar.projectKey=incluit_OpenVino-Alert-Manager -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=52d4a76ab7a5ec115c7b02f04a024f5607767842'
           - docker ps -a
           - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
           - docker tag docker-zmq-pub  openvinoincluit/alertmanager:latest
           - docker push openvinoincluit/alertmanager:latest
           - docker stop docker-pub-server
           - docker rm docker-pub-server
           - docker images
           - docker system prune -a -f

    - stage: Validation
      if: branch = master
      script:
           - docker pull openvinoincluit/alertmanager:latest
           - echo 'The Pipeline was validated!!!!'