os: linux
dist: bionic
language: python

services:
  - docker

jobs:
  include:
    - stage: Docker
      if: branch = master
      script:
           - sudo apt-get update
           - docker build -t docker-zmq-pub .
           - docker run -d --name docker-pub-server -p 5000:5000 -p 4444:4444 -t docker-zmq-pub
           - docker ps -a
           - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
           - docker tag docker-zmq-pub  openvinoincluit/alertmanager:latest
           - docker push openvinoincluit/alertmanager:latest
           - docker stop docker-pub-server
           - docker rm docker-pub-server
           - docker images
           - docker system prune -a -f

    - stage: Validation
      if: branch = master
      script:
           - docker pull openvinoincluit/alertmanager:latest
           - echo 'The Pipeline was validated!!!!'