os: linux
dist: bionic
language: cpp

services:
  - docker

jobs:
  include:
    - stage: Install
      script: sudo apt-get update

    - stage: Docker
      script:
           - docker build -t docker-zmq-pub .
           - docker run --name docker-pub-server -p 5000:5000 -p 4444:4444 -t docker-zmq-pub
           - docker ps
           - docker images
           - docker system prune -a -f

    - stage: Validation
      script:
           - echo 'The Pipeline was validated!!!!'